resolver: lts-11.8
packages:
- .
extra-deps:
- git: git@github.com:NorfairKing/validity.git
  commit: a86dd3e4830c14c056a0d5d8712864d395d25b2a
  subdirs:
    - validity
    - validity-time
    - genvalidity
    - genvalidity-time
    - genvalidity-property
    - genvalidity-hspec
