name: pretty-relative-time
version: 0.3.0.0
github: "NorfairKing/pretty-relative-time"
license: MIT
author: "Tom Sydney Kerckhove"
maintainer: "syd.kerckhove@gmail.com"
copyright: "Copyright: (c) 2018-2022 Tom Sydney Kerckhove"

extra-source-files:
- CHANGELOG.md

synopsis: Pretty relative time
category: Time

dependencies:
- base >= 4.7 && < 5
- time
- validity
- validity-time

library:
  source-dirs: src
  ghc-options:
    - -Wall

tests:
  pretty-relative-time-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - pretty-relative-time
    - hspec
    - QuickCheck
    - genvalidity >=1.0
    - genvalidity-hspec
    - genvalidity-time
